name: Feature Request
description: Suggest an idea for this project.
labels: ["enhancement"]
body:
  - type: textarea
    attributes:
      label: Feature description
      description: |
        Provide a clear and concise description of what you want to happen.
        Include screenshots, wireframes, mockups, diagrams, or other supporting artifacts if available.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Use case
      description: |
        Why do you need this feature? For example: "I'm always frustrated when..."
    validations:
      required: true
  - type: textarea
    attributes:
      label: Acceptance Criteria
      description: |
        Provide the criteria that must be met in order for this issue to be considered complete.
        Be specific, and consider potential edge cases. The criteria should be observable and testable.
      placeholder: |
        Given a user or system is in ... (a page, workflow, or state)
        And ... (optional other criteria that needs to be met)
        When the user ... (action)
        Then ... (expected outcome)
        And ... (additional observable outcome)
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposed solution
      description: Describe a possible solution or any technical considerations, if known.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Potential Impact
      description: |
        Discuss any potential impacts of this feature on existing functionality or performance, if known.
        Will this feature cause breaking changes?
        What challenges might arise?
    validations:
      required: false
